/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author HuyNhan
 */
public class Frm_dangky extends javax.swing.JFrame {

    /**
     * Creates new form Frm_dangky
     */
    public Frm_dangky() {
        initComponents();
        getRootPane().setDefaultButton(btn_dangky);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnt_thongtin = new javax.swing.JPanel();
        lbl_hoten = new javax.swing.JLabel();
        lbl_taikhoan = new javax.swing.JLabel();
        lbl_matkhau = new javax.swing.JLabel();
        lbl_nhaplaiMK = new javax.swing.JLabel();
        lbl_diachi = new javax.swing.JLabel();
        lbl_ngaysinh = new javax.swing.JLabel();
        lbl_gioitinh = new javax.swing.JLabel();
        lbl_sdt = new javax.swing.JLabel();
        lbl_quyen = new javax.swing.JLabel();
        lbl_ghichu = new javax.swing.JLabel();
        txt_hoten = new javax.swing.JTextField();
        txt_taikhoan = new javax.swing.JTextField();
        txt_ngaysinh = new javax.swing.JTextField();
        txt_diachi = new javax.swing.JTextField();
        txt_sdt = new javax.swing.JTextField();
        txt_ghichu = new javax.swing.JTextField();
        cbb_gioitinh = new javax.swing.JComboBox<>();
        cbb_quyen = new javax.swing.JComboBox<>();
        pwd_mk = new javax.swing.JPasswordField();
        pwd_nhaplaimk = new javax.swing.JPasswordField();
        pnl_button = new javax.swing.JPanel();
        btn_dangky = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        btn_dangnhap = new javax.swing.JButton();
        pnl_tieude = new javax.swing.JPanel();
        lbl_tieude = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Đăng Ký Tài Khoản");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnt_thongtin.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Điền Thông Tin", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        lbl_hoten.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_hoten.setText("Họ Và Tên : ");

        lbl_taikhoan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_taikhoan.setText("Tài khoản :");

        lbl_matkhau.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_matkhau.setText("Mật Khẩu");

        lbl_nhaplaiMK.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_nhaplaiMK.setText("Nhập Lại Mật Khẩu :");

        lbl_diachi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_diachi.setText("Địa Chỉ :");

        lbl_ngaysinh.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_ngaysinh.setText("Ngày Sinh : ");

        lbl_gioitinh.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_gioitinh.setText("Giới Tính :");

        lbl_sdt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_sdt.setText("Số Điện Thoại");

        lbl_quyen.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_quyen.setText("Quyền :");

        lbl_ghichu.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_ghichu.setText("Ghi Chú :");

        txt_hoten.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txt_taikhoan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txt_ngaysinh.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txt_diachi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txt_sdt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txt_ghichu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        cbb_gioitinh.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbb_gioitinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        cbb_quyen.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        pwd_mk.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        pwd_nhaplaimk.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout pnt_thongtinLayout = new javax.swing.GroupLayout(pnt_thongtin);
        pnt_thongtin.setLayout(pnt_thongtinLayout);
        pnt_thongtinLayout.setHorizontalGroup(
            pnt_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnt_thongtinLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnt_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnt_thongtinLayout.createSequentialGroup()
                        .addComponent(lbl_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnt_thongtinLayout.createSequentialGroup()
                        .addComponent(lbl_matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pwd_mk, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnt_thongtinLayout.createSequentialGroup()
                        .addComponent(lbl_nhaplaiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pwd_nhaplaimk, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnt_thongtinLayout.createSequentialGroup()
                        .addComponent(lbl_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnt_thongtinLayout.createSequentialGroup()
                        .addComponent(lbl_taikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_taikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnt_thongtinLayout.createSequentialGroup()
                        .addComponent(lbl_gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbb_gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnt_thongtinLayout.createSequentialGroup()
                        .addComponent(lbl_ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnt_thongtinLayout.createSequentialGroup()
                        .addComponent(lbl_quyen, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbb_quyen, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnt_thongtinLayout.createSequentialGroup()
                        .addComponent(lbl_ghichu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_ghichu, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnt_thongtinLayout.createSequentialGroup()
                        .addComponent(lbl_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnt_thongtinLayout.setVerticalGroup(
            pnt_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnt_thongtinLayout.createSequentialGroup()
                .addGroup(pnt_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnt_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_taikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_taikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnt_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwd_mk, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnt_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nhaplaiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwd_nhaplaimk, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnt_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbb_gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnt_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnt_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnt_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnt_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_quyen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbb_quyen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnt_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ghichu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ghichu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pnl_button.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Phím Chức Năng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        btn_dangky.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_dangky.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baitap/images/Add.png"))); // NOI18N
        btn_dangky.setText("Đăng Ký");
        btn_dangky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangkyActionPerformed(evt);
            }
        });

        btn_reset.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baitap/images/Delete.png"))); // NOI18N
        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        btn_dangnhap.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_dangnhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baitap/images/Profile.png"))); // NOI18N
        btn_dangnhap.setText("Đăng Nhập");
        btn_dangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangnhapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_buttonLayout = new javax.swing.GroupLayout(pnl_button);
        pnl_button.setLayout(pnl_buttonLayout);
        pnl_buttonLayout.setHorizontalGroup(
            pnl_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_buttonLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnl_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_reset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_dangky, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_dangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        pnl_buttonLayout.setVerticalGroup(
            pnl_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_buttonLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(btn_dangnhap)
                .addGap(60, 60, 60)
                .addComponent(btn_dangky, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_tieude.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_tieude.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lbl_tieude.setForeground(new java.awt.Color(0, 0, 153));
        lbl_tieude.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_tieude.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baitap/images/News.png"))); // NOI18N
        lbl_tieude.setText("  Đăng Ký  ");

        javax.swing.GroupLayout pnl_tieudeLayout = new javax.swing.GroupLayout(pnl_tieude);
        pnl_tieude.setLayout(pnl_tieudeLayout);
        pnl_tieudeLayout.setHorizontalGroup(
            pnl_tieudeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tieudeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_tieude, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_tieudeLayout.setVerticalGroup(
            pnl_tieudeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tieudeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_tieude)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnl_tieude, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnt_thongtin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnl_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_tieude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnt_thongtin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
        int luachon = JOptionPane.showConfirmDialog(new JFrame(), "Bạn có muốn thoát không", "Thông báo thoát", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (luachon == JOptionPane.YES_OPTION) {
            System.exit(0);
        }else if (luachon == JOptionPane.NO_OPTION) {
        }
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
        DoDLVaoCBBQuyen();
        
        
    }//GEN-LAST:event_formWindowOpened

    private void btn_dangkyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangkyActionPerformed
        System.out.println(cbb_gioitinh.getSelectedIndex());
        MyCombobox cbb = (MyCombobox)cbb_quyen.getSelectedItem();
        String hoten,taikhoan,matkhau,nhaplaimk,ngaysinh,diachi,sdt,ghichu,quyen;
        int gioitinh;
        hoten = txt_hoten.getText();
        taikhoan = txt_taikhoan.getText();
        matkhau = String.valueOf(pwd_mk.getPassword());
        nhaplaimk = String.valueOf(pwd_nhaplaimk.getPassword());
        ngaysinh = txt_ngaysinh.getText();
        diachi = txt_diachi.getText();
        sdt = txt_sdt.getText();
        ghichu = txt_ghichu.getText();
        quyen = (String) cbb.Value;
        gioitinh = cbb_gioitinh.getSelectedIndex();
        
        String query1 = " select * from NHANVIEN where NHANVIEN.TENDANGNHAP = N'"+taikhoan+"'";
        
        ResultSet rs = Assignment.connection.ExcuteQuerySelect(query1);
        
        
        if (hoten.equals("")||taikhoan.equals("")||matkhau.equals("")||nhaplaimk.equals("")||ngaysinh.equals("")||diachi.equals("")||sdt.equals("")||ghichu.equals("")) {
            JOptionPane.showMessageDialog(new JFrame(), "Bạn không được để trống bất kì ô nào", "Thông báo Đăng Ký", JOptionPane.WARNING_MESSAGE);
        }else if (!matkhau.equals(nhaplaimk)) {
            JOptionPane.showMessageDialog(new JFrame(), "Mật khẩu không trùng nhau", "Thông báo Đăng Ký", JOptionPane.WARNING_MESSAGE);
        }else try {
            if (rs.next()) {
                JOptionPane.showMessageDialog(new JFrame(), "Tài Khoản Đã Tồn Tại", "Thông báo Đăng Ký", JOptionPane.WARNING_MESSAGE);
            }else{
                String query = "insert into NHANVIEN(TENNV,DIACHI,GIOITINH,NGAYSINH,SDT,TENDANGNHAP,MATKHAU,MAQUYEN,GHICHU) values (N'"
                    +hoten+"', N'"+diachi+"', "+gioitinh+", '"+ngaysinh+"', '"+sdt+"', N'"+taikhoan+"', N'"+matkhau+"',"+quyen+", N'"+ghichu+"')" ;  


                int kq = Assignment.connection.ExcuteNonQuery(query);

                if(kq<0){
                    System.out.println("Lỗi Đăng ký dữ liệu !!!");
                }
                else if (kq == 0){
                System.out.println("Không có dòng nào được thêm");
                }
                else{
                    JOptionPane.showMessageDialog(new JFrame(), "Đăng ký thành công", "Thông Báo", JOptionPane.NO_OPTION);
                }
            }
        } catch (SQLException ex) {
            System.out.println("Lỗi truy vấn " + ex.getMessage());
        }

            
        
        
    }//GEN-LAST:event_btn_dangkyActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        txt_diachi.setText("");
        txt_ghichu.setText("");
        txt_hoten.setText("");
        pwd_mk.setText("");
        txt_ngaysinh.setText("");
        pwd_nhaplaimk.setText("");
        txt_sdt.setText("");
        txt_taikhoan.setText("");
        cbb_gioitinh.setSelectedIndex(0);
        cbb_quyen.setSelectedIndex(0);
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_dangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangnhapActionPerformed
    int luachon = JOptionPane.showConfirmDialog(new JFrame(), "Bạn có muốn thoát không", "Thông báo thoát", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (luachon == JOptionPane.YES_OPTION) {
            this.dispose();
            Assignment.frmdn.show();
        }else if (luachon == JOptionPane.NO_OPTION) {
        }
    }//GEN-LAST:event_btn_dangnhapActionPerformed
    public void DoDLVaoCBBQuyen(){
        try {
            String query ="select * from QUYEN";
            ResultSet rs = Assignment.connection.ExcuteQuerySelect(query);
            
            DefaultComboBoxModel cbbModel = new DefaultComboBoxModel();
            
            while (rs.next()){
                MyCombobox item = new MyCombobox( rs.getString("TENQUYEN"), rs.getString("MAQUYEN"));
                cbbModel.addElement(item);
            }
            cbb_quyen.setModel(cbbModel);
        } catch (SQLException ex) {
            System.out.println("Lỗi truy vấn dữ liệu. "+ex.getMessage());
        }
        
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_dangky.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_dangky.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_dangky.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_dangky.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_dangky().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dangky;
    private javax.swing.JButton btn_dangnhap;
    private javax.swing.JButton btn_reset;
    private javax.swing.JComboBox<String> cbb_gioitinh;
    private javax.swing.JComboBox<String> cbb_quyen;
    private javax.swing.JLabel lbl_diachi;
    private javax.swing.JLabel lbl_ghichu;
    private javax.swing.JLabel lbl_gioitinh;
    private javax.swing.JLabel lbl_hoten;
    private javax.swing.JLabel lbl_matkhau;
    private javax.swing.JLabel lbl_ngaysinh;
    private javax.swing.JLabel lbl_nhaplaiMK;
    private javax.swing.JLabel lbl_quyen;
    private javax.swing.JLabel lbl_sdt;
    private javax.swing.JLabel lbl_taikhoan;
    private javax.swing.JLabel lbl_tieude;
    private javax.swing.JPanel pnl_button;
    private javax.swing.JPanel pnl_tieude;
    private javax.swing.JPanel pnt_thongtin;
    private javax.swing.JPasswordField pwd_mk;
    private javax.swing.JPasswordField pwd_nhaplaimk;
    private javax.swing.JTextField txt_diachi;
    private javax.swing.JTextField txt_ghichu;
    private javax.swing.JTextField txt_hoten;
    private javax.swing.JTextField txt_ngaysinh;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JTextField txt_taikhoan;
    // End of variables declaration//GEN-END:variables
}
