/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author HuyNhan
 */
public class Frm_DoiMK extends javax.swing.JFrame {

    /**
     * Creates new form Frm_DoiMK
     */
    public Frm_DoiMK() {
        initComponents();
        getRootPane().setDefaultButton(btn_doimk);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_DoiMK = new javax.swing.JPanel();
        lbl_taikhoan = new javax.swing.JLabel();
        lbl_MKcu = new javax.swing.JLabel();
        lbl_MKmoi = new javax.swing.JLabel();
        lbl_nhaplaiMK = new javax.swing.JLabel();
        txt_taikhoan = new javax.swing.JTextField();
        pwd_mkcu = new javax.swing.JPasswordField();
        pwd_mkmoi = new javax.swing.JPasswordField();
        pwd_nhaplaimk = new javax.swing.JPasswordField();
        pnl_button = new javax.swing.JPanel();
        btn_reset = new javax.swing.JButton();
        btn_doimk = new javax.swing.JButton();
        btn_dangnhap = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Đổi Mật Khẩu");
        setBackground(new java.awt.Color(0, 255, 0));
        setFocusTraversalPolicyProvider(true);
        setMinimumSize(new java.awt.Dimension(585, 250));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnl_DoiMK.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Điền Thông Tin", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        lbl_taikhoan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_taikhoan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_taikhoan.setText("Tài Khoản : ");

        lbl_MKcu.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_MKcu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_MKcu.setText("Mật Khẩu Cũ :");

        lbl_MKmoi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_MKmoi.setText("Mật Khẩu Mới : ");

        lbl_nhaplaiMK.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_nhaplaiMK.setText("Nhập Lại Mật Khẩu :");

        txt_taikhoan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        pwd_mkcu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        pwd_mkmoi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        pwd_nhaplaimk.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout pnl_DoiMKLayout = new javax.swing.GroupLayout(pnl_DoiMK);
        pnl_DoiMK.setLayout(pnl_DoiMKLayout);
        pnl_DoiMKLayout.setHorizontalGroup(
            pnl_DoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_DoiMKLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_DoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_DoiMKLayout.createSequentialGroup()
                        .addComponent(lbl_MKcu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pwd_mkcu))
                    .addGroup(pnl_DoiMKLayout.createSequentialGroup()
                        .addComponent(lbl_MKmoi, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pwd_mkmoi))
                    .addGroup(pnl_DoiMKLayout.createSequentialGroup()
                        .addComponent(lbl_taikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_taikhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                    .addGroup(pnl_DoiMKLayout.createSequentialGroup()
                        .addComponent(lbl_nhaplaiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pwd_nhaplaimk)))
                .addContainerGap())
        );
        pnl_DoiMKLayout.setVerticalGroup(
            pnl_DoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_DoiMKLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_DoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_DoiMKLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txt_taikhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                    .addComponent(lbl_taikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnl_DoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_DoiMKLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(pwd_mkcu, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                    .addComponent(lbl_MKcu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnl_DoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_DoiMKLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(pwd_mkmoi, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                    .addComponent(lbl_MKmoi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnl_DoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_DoiMKLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(pwd_nhaplaimk, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                    .addComponent(lbl_nhaplaiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnl_button.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Các Phím Chức Năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        btn_reset.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baitap/images/Load.png"))); // NOI18N
        btn_reset.setText("Reset");
        btn_reset.setIconTextGap(1);
        btn_reset.setMaximumSize(new java.awt.Dimension(133, 40));
        btn_reset.setMinimumSize(new java.awt.Dimension(133, 40));
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        btn_doimk.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_doimk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baitap/images/Save.png"))); // NOI18N
        btn_doimk.setText("UpLoad");
        btn_doimk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_doimkActionPerformed(evt);
            }
        });

        btn_dangnhap.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_dangnhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baitap/images/Exit.png"))); // NOI18N
        btn_dangnhap.setText("Đăng Nhập");
        btn_dangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangnhapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_buttonLayout = new javax.swing.GroupLayout(pnl_button);
        pnl_button.setLayout(pnl_buttonLayout);
        pnl_buttonLayout.setHorizontalGroup(
            pnl_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_buttonLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pnl_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_doimk, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(btn_reset, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_dangnhap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnl_buttonLayout.setVerticalGroup(
            pnl_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_buttonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_doimk, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_dangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_DoiMK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_DoiMK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_doimkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_doimkActionPerformed
        String taikhoan, mkcu, mkmoi, nhaplaimk;
        taikhoan = txt_taikhoan.getText();
        mkcu = String.valueOf(pwd_mkcu.getPassword());
        mkmoi = String.valueOf(pwd_mkmoi.getPassword());
        nhaplaimk = String.valueOf(pwd_nhaplaimk.getPassword());
        String query = "select * from NHANVIEN where NHANVIEN.TENDANGNHAP = N'"+taikhoan+"' and NHANVIEN.MATKHAU = N'"+mkcu+"'";
        
        ResultSet rs = Assignment.connection.ExcuteQuerySelect(query);
        
        if (taikhoan.equals("") || mkcu.equals("") || mkmoi.equals("") || nhaplaimk.equals("")) {
            JOptionPane.showMessageDialog(new JFrame(), "Bạn không được để trống bất kì ô nào", "Thông báo", JOptionPane.WARNING_MESSAGE);
        } else if (!mkmoi.equals(nhaplaimk)) {
            JOptionPane.showMessageDialog(new JFrame(), "Mật khẩu mới không trùng nhau", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }  else try {
            if (rs.next()) {
                String query1 ;  
                query1 = "update NHANVIEN set NHANVIEN.MATKHAU = N'"+mkmoi+"' where NHANVIEN.TENDANGNHAP = N'"+taikhoan+"'";
                int kq = Assignment.connection.ExcuteNonQuery(query1);

                if(kq<0){
                    System.out.println("Lỗi thêm dữ liệu !!!");
                }else if (kq == 0){
                    System.out.println("Không có dòng nào được thêm");
                }else{
                    JOptionPane.showMessageDialog(new JFrame(), "Đổi Mật khẩu thành công", "Thông Báo", JOptionPane.NO_OPTION);
                }
            }else{
                JOptionPane.showMessageDialog(new JFrame(), "Tài khoản & Mật khẩu sai", "Thông báo", JOptionPane.WARNING_MESSAGE);
            }
        } catch (SQLException ex) {
            System.out.println("Lỗi truy vấn " + ex.getMessage());
        }
 
            
        
        
        
    }//GEN-LAST:event_btn_doimkActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        
        pwd_mkcu.setText("");
        pwd_mkmoi.setText("");
        pwd_nhaplaimk.setText("");
        txt_taikhoan.setText("");
        
        
    }//GEN-LAST:event_btn_resetActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int luachon = JOptionPane.showConfirmDialog(new JFrame(), "Bạn có muốn thoát không", "Thông báo thoát", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (luachon == JOptionPane.YES_OPTION) {
            System.exit(0);
        }else if (luachon == JOptionPane.NO_OPTION) {
            
        }
    }//GEN-LAST:event_formWindowClosing

    private void btn_dangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangnhapActionPerformed
        int luachon = JOptionPane.showConfirmDialog(new JFrame(), "Bạn có muốn thoát không", "Thông báo thoát", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (luachon == JOptionPane.YES_OPTION) {
            this.dispose();
            Assignment.frmdn.show();
        }else if (luachon == JOptionPane.NO_OPTION) {
            
        }
    }//GEN-LAST:event_btn_dangnhapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_DoiMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_DoiMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_DoiMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_DoiMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_DoiMK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dangnhap;
    private javax.swing.JButton btn_doimk;
    private javax.swing.JButton btn_reset;
    private javax.swing.JLabel lbl_MKcu;
    private javax.swing.JLabel lbl_MKmoi;
    private javax.swing.JLabel lbl_nhaplaiMK;
    private javax.swing.JLabel lbl_taikhoan;
    private javax.swing.JPanel pnl_DoiMK;
    private javax.swing.JPanel pnl_button;
    private javax.swing.JPasswordField pwd_mkcu;
    private javax.swing.JPasswordField pwd_mkmoi;
    private javax.swing.JPasswordField pwd_nhaplaimk;
    private javax.swing.JTextField txt_taikhoan;
    // End of variables declaration//GEN-END:variables
}
