/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Administrator
 */
public class frmDangNhap extends javax.swing.JFrame {

    /**
     * Creates new form frmDangNhap
     */
    public frmDangNhap() {
        initComponents();
        getRootPane().setDefaultButton(btnDangNhap);
    }
    
    public static String MaQuyen;
    public static String MaNV;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlTop = new javax.swing.JPanel();
        LblTitle = new javax.swing.JLabel();
        PnlMiddle = new javax.swing.JPanel();
        LblHinh = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        txtTenDangNhap = new javax.swing.JTextField();
        lblPass = new javax.swing.JLabel();
        pwdMatKhau = new javax.swing.JPasswordField();
        btnDangNhap = new javax.swing.JButton();
        bntDangKi = new javax.swing.JButton();
        lblHinh = new javax.swing.JLabel();
        chb_nhomatkhau = new javax.swing.JCheckBox();
        bntdoiMK = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Đăng Nhập");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusTraversalPolicyProvider(true);
        setLocationByPlatform(true);
        setResizable(false);
        setSize(new java.awt.Dimension(462, 365));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        PnlTop.setBackground(new java.awt.Color(102, 255, 51));

        LblTitle.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        LblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTitle.setText("Đăng nhập hệ thống");

        javax.swing.GroupLayout PnlTopLayout = new javax.swing.GroupLayout(PnlTop);
        PnlTop.setLayout(PnlTopLayout);
        PnlTopLayout.setHorizontalGroup(
            PnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PnlTopLayout.setVerticalGroup(
            PnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        PnlMiddle.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, java.awt.Color.orange));

        lblUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUser.setForeground(new java.awt.Color(0, 102, 204));
        lblUser.setText("Tài Khoản");

        lblPass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPass.setForeground(new java.awt.Color(0, 102, 204));
        lblPass.setText("Mật Khẩu");

        btnDangNhap.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baitap/images/Log-Out-icon_32.png"))); // NOI18N
        btnDangNhap.setText("ĐĂNG NHẬP");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });

        bntDangKi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bntDangKi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baitap/images/Modify.png"))); // NOI18N
        bntDangKi.setText("ĐĂNG  KÍ");
        bntDangKi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntDangKiActionPerformed(evt);
            }
        });

        lblHinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baitap/images/icon_hris.jpg"))); // NOI18N

        chb_nhomatkhau.setText("      Nhớ mật khẩu");

        bntdoiMK.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bntdoiMK.setText("Đổi Mật Khẩu");
        bntdoiMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntdoiMKActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baitap/images/Exit.png"))); // NOI18N
        jButton1.setText("Thoát");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlMiddleLayout = new javax.swing.GroupLayout(PnlMiddle);
        PnlMiddle.setLayout(PnlMiddleLayout);
        PnlMiddleLayout.setHorizontalGroup(
            PnlMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlMiddleLayout.createSequentialGroup()
                .addGroup(PnlMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlMiddleLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(LblHinh)
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlMiddleLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PnlMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(15, 15, 15)))
                .addGroup(PnlMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlMiddleLayout.createSequentialGroup()
                        .addGroup(PnlMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlMiddleLayout.createSequentialGroup()
                                .addComponent(bntDangKi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(bntdoiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnDangNhap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlMiddleLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(PnlMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlMiddleLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                        .addGap(23, 23, 23))
                                    .addGroup(PnlMiddleLayout.createSequentialGroup()
                                        .addComponent(lblPass, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                        .addGap(27, 27, 27)))
                                .addGroup(PnlMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pwdMatKhau)
                                    .addComponent(txtTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(PnlMiddleLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(chb_nhomatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        PnlMiddleLayout.setVerticalGroup(
            PnlMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlMiddleLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(LblHinh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHinh)
                    .addGroup(PnlMiddleLayout.createSequentialGroup()
                        .addGroup(PnlMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PnlMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pwdMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chb_nhomatkhau)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PnlMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bntdoiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bntDangKi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PnlMiddle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PnlTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PnlMiddle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    DBConnection connection = new DBConnection();
    public frmDangNhap(JLabel LblHinh, JLabel LblTitle, JPanel PnlMiddle, JPanel PnlTop, JButton bntDangKi, JButton btnDangNhap, JLabel lblHinh, JLabel lblPass, JLabel lblUser, JPasswordField pwdMatKhau, JTextField txtTenDangNhap) throws HeadlessException {
        this.LblHinh = LblHinh;
        this.LblTitle = LblTitle;
        this.PnlMiddle = PnlMiddle;
        this.PnlTop = PnlTop;
        this.bntDangKi = bntDangKi;
        this.btnDangNhap = btnDangNhap;
        this.lblHinh = lblHinh;
        this.lblPass = lblPass;
        this.lblUser = lblUser;
        this.pwdMatKhau = pwdMatKhau;
        this.txtTenDangNhap = txtTenDangNhap;
    }
    
    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        String tenDN, matKhau;
        tenDN = txtTenDangNhap.getText().trim();
        
        matKhau= String.valueOf(pwdMatKhau.getPassword()).trim();
        
        String query = "select * from NHANVIEN where NHANVIEN.TENDANGNHAP = N'"+tenDN+"' and NHANVIEN.MATKHAU = N'"+matKhau+"'";
        ResultSet rs = connection.ExcuteQuerySelect(query);
        String query1 = "select * from NHANVIEN";
        ResultSet rs1 = connection.ExcuteQuerySelect(query1);
        try {
            if(rs.next()){
                MaQuyen = rs.getString("MAQUYEN");
                MaNV = rs.getString("MANV");
                if (chb_nhomatkhau.isSelected()) {// nếu checkbox nhớ được chọn
                }else{
                    pwdMatKhau.setText("");
                }
                Assignment.frmdn.dispose();
                Assignment.frmmain.show();
                
            }else{
                
                JOptionPane.showMessageDialog(new JFrame(), "Đăng nhập thất bại", "Thông báo đăng nhập", JOptionPane.WARNING_MESSAGE);
            }
        } catch (SQLException ex) {
            System.out.println("Lỗi truy vấn " + ex.getMessage());
        }
        
        
        
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void bntDangKiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntDangKiActionPerformed
        this.dispose();
        Assignment.frmdk.show();
        
    }//GEN-LAST:event_bntDangKiActionPerformed

    private void bntdoiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntdoiMKActionPerformed
        this.dispose();
        Assignment.frmdoimk.show();
        
    }//GEN-LAST:event_bntdoiMKActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Thoat();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Thoat();
    }//GEN-LAST:event_formWindowClosing
    
    public void Thoat(){
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        int kQ = JOptionPane.showConfirmDialog(null,
                "Bạn có muốn thoát chương trình không ?","Confirm",JOptionPane.YES_NO_OPTION);
        if(kQ == 0){
            System.exit(0);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblHinh;
    private javax.swing.JLabel LblTitle;
    private javax.swing.JPanel PnlMiddle;
    private javax.swing.JPanel PnlTop;
    private javax.swing.JButton bntDangKi;
    private javax.swing.JButton bntdoiMK;
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JCheckBox chb_nhomatkhau;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblHinh;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPasswordField pwdMatKhau;
    private javax.swing.JTextField txtTenDangNhap;
    // End of variables declaration//GEN-END:variables


}
